---
title: "7.9.11 GAM with backfitting approach"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1. data generation
```{R}
set.seed(5)
x1 = rnorm(100, sd=2)
x2 = rnorm(100, sd=sqrt(2))
eps = rnorm(100, sd = 1)
b0 = 5; b1=2.5 ; b2=11.5
y = b0 +b1*x1 + b2*x2 + eps
```


2.beta b test
```{r}
beta1=1
a=y-beta1*x1
beta2=lm(a~x2)$coef
beta2

beta2=10
a=y-beta2*x2
beta1=lm(a~x1)$coef
beta1
```

3. beta test loop
```{R}
beta.df = data.frame("beta0"=rep(0,1000),"beta1"=rep(0,1000),"beta2"=rep(0,1000))
beta1 = 0
beta2=0

for (i in 1:1000){
  a=y-beta1*x1
  model = lm(a~x2)
  beta2 = model$coef[2]
  beta.df$beta2[i]= beta2
  a=y-beta2*x2
  model = lm(a~x1)
  beta1 = model$coef[2]
  beta.df$beta1[i]=beta1
  
  beta.df$beta0[i]=model$coef[1]
}
beta.df


plot(1:1000,beta.df$beta2,ylim=range(0:12),type='l', lwd="3", col="blue",
xlab="Iteration",ylab="Coefficient value")
title("Coefficients found by iterating, and overlaid values from lm() function.")
lines(1:1000,beta.df$beta1, col="red", lwd=3)
lines(1:1000,beta.df$beta0, col="green",lwd=3)

#compare to lm function
lm.fit=lm(y~x1+x2)
coef(lm.fit)

abline(h=4.996049, lty=2, lwd=2)
abline(h=2.526440, lty=2, lwd=2, col="yellow")
abline(h=11.536752, lty=2, lwd=2, col="green")
```

