---
title: "12. chapter 3 exercise 13"
output: html_document
---

13.In this exercise you will create some simulated data and will fit simple linear regression models to it. Make sure to use set.seed(1) prior to starting part (a) to ensure consistent results.
(a) Using the rnorm() function, create a vector, x, containing 100 observations drawn from a N(0, 1) distribution. This represents afeature, X.
(b) Using the rnorm() function, create a vector, eps, containing 100 observations drawn from a N(0, 0.25) distribution i.e. a normal distribution with mean zero and variance 0.25.
(c) Using x and eps, generate a vector y according to the model Y = −1+0.5X + .
(3.39)
What is the length of the vector y? What are the values of β0 and β1 in this linear model?
100,
(d) Create a scatterplot displaying the relationship between x and y. Comment on what you observe.
(e) Fit a least squares linear model to predict y using x. Comment on the model obtained. How do
βˆ0 and ˆβ1 compare to β0 and β1?
(f) Display the least squares line on the scatterplot obtained in (d). Draw the population regression line on the plot, in a different color. Use the legend() command to create an appropriate legend.
(g) Now fit a polynomial regression model that predicts y using x and x2
. Is there evidence that the quadratic term improves the model fit? Explain your answer.

```{R}
set.seed(1)
x=rnorm(100,mean=0,sd=1)
eps=rnorm(100,mean=0,sd=0.25)
eps
y=-1+0.5*x+eps
fit <- lm(y~x)
fit
plot(x,y)
abline(fit)
summary(fit)
fit1 <- lm(y~x+I(x^2))
summary(fit1)
confint(fit)
```

(h) Repeat (a)–(f) after modifying the data generation process in such a way that there is less noise in the data. The model (3.39) should remain the same. You can do this by decreasing the variance of the normal distribution used to generate the error term  in (b). Describe your results.
(i) Repeat (a)–(f) after modifying the data generation process in such a way that there is more noise in the data. The model (3.39) should remain the same. You can do this by increasing the variance of the normal distribution used to generate the error term  in (b). Describe your results.
(j) What are the confidence intervals for β0 and β1 based on the original data set, the noisier data set, and the less noisy data set? Comment on your results.

```{R}
eps1 <- rnorm(100,mean=0,sd=2)
y1=-1+0.5*x+eps1
fit3 <- lm(y1~x)
summary(fit3)
```
