---
title: "12 Chapter 3 exercise 15"
output: html_document
---
15. This problem involves the Boston data set, which we saw in the lab for this chapter. We will now try to predict per capita crime rate using the other variables in this data set. In other words, per capita crime rate is the response, and the other variables are the predictors.
(a) For each predictor, fit a simple linear regression model to predict the response. Describe your results. In which of the models is there a statistically significant association between the predictor and the response? Create some plots to back up your assertions.
reject null: zn,indus,nox，rm，age，dis，rad，tax， ptratio，black，lstat，medv
```{R}
library(ISLR)
library(MASS)
head(Boston)
fit <- lm(crim~.,data=Boston)
summary(fit)
```
(b) Fit a multiple regression model to predict the response using all of the predictors. Describe your results. For which predictors can we reject the null hypothesis H0 : βj =0?
```{R}
library(ISLR)
library(MASS)
head(Boston)
fit <- lm(crim~.,data=Boston)
summary(fit)
```

reject null: zn,dis,rad,black ,medv

(c) How do your results from (a) compare to your results from (b)? Create a plot displaying the univariate regression coefficients from (a) on the x-axis, and the multiple regression coefficients from (b) on the y-axis. That is, each predictor is displayed as a single point in the plot. Its coefficient in a simple linear regression model is shown on the x-axis, and its coefficient estimate in the multiple linear regression model is shown on the y-axis.
(d) Is there evidence of non-linear association between any of the predictors and the response? To answer this question, for each predictor X, fit a model of the form
Y = β0 + β1X + β2X2 + β3X3 + .