---
title: "4.4.6 BOOTSTRAPPING"
output: github_document
---

6. We continue to consider the use of a logistic regression model to predict the probability of default using income and balance on the Default data set. In particular, we will now compute estim?tes for the standard errors of the income and balance logistic regression coefficients in two different ways: (1) using the bootstrap, and (2) using the standard formula for computing the standard errors in the glm() function. Do not forget to set a random?seed before beginning your analysis.

(a)Using the summary() and glm() functions, determine the estimated standard errors for the coefficients associated with income and balance in a multiple logistic regression model that uses both predictors.
```{r}
libr?ry(ISLR)
library(MASS)
set.seed(111)
require(caTools)
attach(Default)
fit.default <- glm(default~income+balance,family=binomial(link="logit"))
summary(fit.default)$coefficients
# income = 4.985167e-06
# balance =2.273731e-04
```

(b) Write a function, boot?fn(), that takes as input the Default data set as well as an index of the observations, and that outputs the coefficient estimates for income and balance in the multiple logistic regression model.

```{R}
library(boot)
boot.fn <- function(data,index){
  de?ault=data$default[index]
  income = data$income[index]
  balance = data$balance[index]
  boot.glm <- glm(default~income+balance, family=binomial)
  return(summary(boot.glm)$coefficients[2:3,2])
}
boot.fn(Default, 1:length(Default$default))
# income =4.9851?7e-06
# balance = 2.273731e-04 
```

(c) Use the boot() function together with your boot.fn() function to estimate the standard errors of the logistic regression coefficients for income and balance.

```{R}
boot(Default, boot.fn, R=100)
# income = 1.569269?-07
# balance = 1.192044e-05
```