---
title: "4.4 Chapter 5.4.5 Exercise cross-validation"
output: github_document
---

(a) Fit a logistic regression model that uses income and balance to predict default.
```{R}
library(ISLR)
library(MASS)
set.seed(1)
require(caTools)
head(Default)
attach(?efault)
fit.default <- glm(default~income+balance,family=binomial(link="logit"))
```

(b) Using the validation set approach, estimate the test error of this model. In order to do this, you must perform the following steps:
  i. Split the sample set into a ?raining set and a validation set.
  ii. Fit a multiple logistic regression model using only the training observations.
  iii. Obtain a prediction of default status for each individual in the validation set by computing the posterior probability of default ?or that individual, and classifying the individual to the default category if the posterior probability is greater than 0.5.
  iv. Compute the validation set error, which is the fraction of the observations in the validation set that are misclassified.
```?R}
#1. 切分数据集 `sample.split`
split<- sample.split(Default$default, SplitRatio = 0.5)
training.set <- subset(Default, split==T)
test.set <- subset(Default, split==F)

#2.拟合训练集
training.fit <- glm(default~balance+income, data= training.set, family=b?nomial)

#3.测试集
test.predict <- predict(training.fit,test.set, type="response")

#4.替换概率值为二项式值
test.dich <- rep("No", length(test.set$default)) #构建新的二项因变量数据集
test.dich[test.predict>0.5] <- "Yes"
test.dich

#5. 统计预测准确度
table(?est.dich, test.set$default)
test.error <- (105+19)/10000
# 0.0124
```

(c) Repeat the process in (b) three times, using three different splits of the observations into a training set and a validation set. Comment o? the results obtained.

```{R}
1. SplitRa?io = 0.3
test.error = (34+160)/10000

2.SplitRatio = 0.7
test.error = (76+17)/10000

3.SplitRatio = 0.9
test.error = (25+3)/10000

```

(d) Now consider a logistic regression model that predicts the probability of ?efault using income, balance, and a dummy?variable for student. Estimate the test error for this model using the validation set approach. Comment on whether or not including a dummy variable for student leads to a reduction in the test error rate.

```{R}
# 1. 切分数据集 `sample.split`
split<- sam?le.split(Default$default, SplitRatio = 0.5)
training.set <- subset(Default, split==T)
test.set <- subset(Default, split==F)

#2.拟合训练集
training.fit <- glm(default~balance+income+student, data= training.set, family=binomial)

#3.测试集
test.predict <- p?edict(training.fit,test.set, type="response")

#4.替换概率值为二项式值
test.dich <- rep("No", length(test.set$default)) #构建新的二项因变量数据集
test.dich[test.predict>0.5] <- "Yes"
test.dich

#5. 统计预测准确度
table(test.dich, test.set$default)
test.err?r <- (114+15)/10000
# 0.0129

# No reduction in the test error rate
```