---
title: "3.7 Á·Ï°12"
output: html_document
---
1.Write a function, Power(), that prints out the result of raising 2 to the 3rd power. In other words, your function should compute 23 and print out the results. Hint: Recall that x^a raises x to the power ?.Use the print() function to output the result.

2.Create a new function, Power2(), that allows you to pass any two numbers, x and a, and prints out the value of x^a.You can do this by beginning your function with the line > Power2 =function (x,a){
You sho?ld be able to call your function by entering, for instance, > Power2 (3,8) on the command line. This should output the value of 38,namely, 6, 561.

```{R}
Power2 <- function(x,a){
    return(x^a);
}
Power2(3,8)

Power <- function(x,a){
   y=1;
    while(a>?){
        y=y*x;
        a=a-1;
    }
     return(y)
}
```

3.Now using the Power3() function, create a plot of f(x)= x2. The x-axis should display a range of integers from 1 to 10, and the y-axis should display x2. Label the axes appropriately, and use a? appropriate title for the figure. Consider displaying either the x-axis, the y-axis, or both on the log-scale. You can do this by using log=¡®¡®x¡¯¡¯, log=¡®¡®y¡¯¡¯,or log=¡®¡®xy¡¯¡¯ as arguments to the plot() function.

```{R}
x=c(1:10)
Power(x,2)
plot(x?Power(x,2))
```

4. Create a function, PlotPower(), that allows you to create a plot of x against x^a for a fixed a and for a range of values of x.For instance, if you call > PlotPower (1:10,3)
then a plot should be created with an x-axis taking on values ?, 2,... , 10, and a y-axis taking on values 13, 23,..., 103.
```{r}
PlotPower <- function(x,a){
  y=1;
  while(a>0){
    y=y*x;
    a=a-1;
    }
  plot(x,y)
}
PlotPower(1:10,3)
```